### ISSUE TITLE
Health parses inputs wrong on 64-bit setup

### ISSUE THREAD

**Issue by LangdalP** [bsc-pm/bots#1]
Hi, I have been running the bots applications, including Health, for a paper I am writing. I have noticed that if Health is run with the `-check` flag, the verification is always unsuccessful. I have tried using `-check` on fft and sort, and there it is successful.

How to reproduce:
1. Git pull latest version (master) or download older bots-1.1.2.tar.gz and extract
2. `./configure` and make on a modern 64-bit setup. I have tried using both gcc and Clang.
3. `cd run && ./run-health.sh -check`

After going through the source, and re-checking compiler output, this is the culprit:
https://github.com/bsc-pm/bots/blob/master/omp-tasks/health/health.c#L561
Which gcc does complain about:
```
health.c:564:21: warning: format ‘%ld’ expects argument of type ‘long int *’, but argument 9 has type ‘int32_t * {aka int *}’ [-Wformat=]
```
For medium inputs, the parameters are incorrectly parsed as follows:
```
Number of levels    = 4
Cities per level    = 36
Population ratio    = 10
Simulation time     = 0    <-- Should be 365
Assess time         = 2
Convalescence time  = 12
Initial seed        = 23
Get sick prob.      = 0.002000
Convalescence prob. = 0.100000
Realloc prob.       = 0.150000
```

Changing the `%ld` format to `%d` fixes the problem. I assume it was `%ld` because it is an old application, and because the seed needed to be atleast 32 bits in the days where it was only guaranteed to be 16 bits. However, on modern setups, this causes a bug.

**Comment by xteruel** [comment]
Hi LangdalP, thanks for reporting the bug. :)
