### ISSUE TITLE
alloca and malloc cast

### ISSUE THREAD

**Issue by lee218llnl** [bsc-pm/bots#5]
There are a several calls to alloca and malloc that try to store the results to non void * variables without casting appropriately. For example in serial/nqueens/nqueens.c line 106, in the find_queens function, the code does this:

	a = alloca(size * sizeof(char));

Where a is a char *. The Intel compiler does not like this.

**Comment by emisilve86** [comment]
Health and nQueens sources leads to produce always executables with UNTIED tasks when compiling with IF-Clause or Final Cut-Off, even when executables with TIED tasks should be produced.

I generated some dump of the object files and indeed the "flag" parameter passed to function "GOMP_task" has always the UNTIED bit set in the aforementioned scenarios.

**Comment by xteruel** [comment]
The PR closes this issue
